version: '2.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=golang
      - POSTGRES_USER=golang
      - POSTGRES_PASSWORD=golang
    ports:
      - "501:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U golang" ]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      homework:
        aliases:
          - postgres

  migration:
    build:
      context: .
    restart: on-failure
    depends_on:
      - db
    command: "./migrations/main"
    networks:
        homework:
          aliases:
            - migrations
  app:
    build:
      context: .
    restart: always
    ports:
      - "500:500"
    depends_on:
      - migration
    command: "./main"
    networks:
      homework:
        aliases:
          - backend

networks:
  homework:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
