version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=golang
      - POSTGRES_USER=golang
      - POSTGRES_PASSWORD=golang
    ports:
      - "501:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U golang" ]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      proxynet:

  migration:
    build:
      context: .
    restart: on-failure
    depends_on:
      - db
    command: "./migrations/main"
    networks:
      proxynet:

  app:
    build:
      context: .
    restart: always
    ports:
      - "500:500"
    depends_on:
      - migration
    command: "./main"
    networks:
      proxynet:

networks:
  proxynet:
    name: homework_network
