CREATE TABLE IF NOT EXISTS "users"
(
    id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name     TEXT,
    username TEXT,
    email    TEXT,
    password TEXT
);

CREATE TABLE IF NOT EXISTS "sessions"
(
    user_id INTEGER,
    token      TEXT,
    expires_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE "users" ADD COLUMN p_id INTEGER;